In [24]:
import torch
x=torch.tensor([2.0],dtype=float,requires_grad=True)
y=x**2+2*x**3
y.backward()
print(x.grad)

tensor([28.], dtype=torch.float64)


In [61]:
x=torch.tensor([14.0])
w=torch.tensor([5.0],requires_grad=True)
b=torch.tensor([2.0],requires_grad=True)
y=w*x+b
target=torch.tensor([10])
loss=(y-target)**2
loss.backward()
print(w.grad)
print(b.grad)
lr = 0.001
w = w - lr * w.grad
b = b - lr * b.grad
y=w*x+b
print("before grad:",loss)
loss=(y-target)**2
print("after grad:",loss)

tensor([1736.])
tensor([124.])
before grad: tensor([3844.], grad_fn=<PowBackward0>)
after grad: tensor([1411.6550], grad_fn=<PowBackward0>)


In [66]:
x=torch.tensor([14.0])
w=torch.tensor([5.0],requires_grad=True)
b=torch.tensor([2.0],requires_grad=True)
target=torch.tensor([10])

for i in range(50):
    y=x*w+b
    loss=(y-target)**2
    loss.backward()
    lr=0.001
    with torch.no_grad():
        w-=lr*w.grad
        b-=lr*b.grad
    w.grad.zero_()
    b.grad.zero_()
    print(f"epoch {i}:{loss.item()}")

epoch 0:3844.0
epoch 1:1411.655029296875
epoch 2:518.4105834960938
epoch 3:190.3790283203125
epoch 4:69.9140396118164
epoch 5:25.674928665161133
epoch 6:9.428757667541504
epoch 7:3.4625794887542725
epoch 8:1.2715822458267212
epoch 9:0.4669692814350128
epoch 10:0.17148803174495697
epoch 11:0.06297630816698074
epoch 12:0.023127328604459763
epoch 13:0.008493155241012573
epoch 14:0.0031191192101687193
epoch 15:0.0011453514453023672
epoch 16:0.00042064860463142395
epoch 17:0.00015446223551407456
epoch 18:5.6732827943051234e-05
epoch 19:2.0832700101891533e-05
epoch 20:7.654126420675311e-06
epoch 21:2.810851583490148e-06
epoch 22:1.0315716281183995e-06
epoch 23:3.795466909650713e-07
epoch 24:1.3904445950174704e-07
epoch 25:5.151741788722575e-08
epoch 26:1.859825715655461e-08
epoch 27:6.883965397719294e-09
epoch 28:2.5547706172801554e-09
epoch 29:9.313225746154785e-10
epoch 30:3.283275873400271e-10
epoch 31:1.1004885891452432e-10
epoch 32:3.2741809263825417e-11
epoch 33:1.4551915228366852e-11
